package bbdd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/** Configuración mínima de JDBC compartida por H2 y MariaDB. */
public class ConexionBD {
    private final String url;
    private final String usuario;
    private final String password;

    /** Usa H2 en archivo si no se han definido variables JDBC para otro motor. */
    public ConexionBD() {
        url = valor("JDBC_URL", "jdbc:h2:file:~/wsdwes_07_jdbc");
        usuario = valor("JDBC_USER", "sa");
        password = valor("JDBC_PASSWORD", "");
    }

    /**
     * Abre una conexión nueva; quien la recibe debe cerrarla.
     *
     * @throws SQLException si el controlador no puede conectar con la base
     */
    public Connection abrir() throws SQLException {
        return DriverManager.getConnection(url, usuario, password);
    }

    /**
     * Prepara el esquema según la base configurada. Con H2 crea la tabla si
     * falta; con MariaDB se usa el script SQL del módulo y no altera su esquema.
     *
     * @throws SQLException si falla la conexión o la creación de la tabla
     */
    public void prepararBaseDatos() throws SQLException {
        if (!url.startsWith("jdbc:h2:")) {
            return;
        }
        try (Connection conexion = abrir(); Statement sentencia = conexion.createStatement()) {
            sentencia.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS productos (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nombre VARCHAR(80) NOT NULL,
                        precio DECIMAL(10, 2) NOT NULL
                    )
                    """);
        }
    }

    /** Lee una variable de entorno o devuelve el valor usado para H2. */
    private String valor(String nombre, String valorPorDefecto) {
        String configurado = System.getenv(nombre);
        return configurado == null ? valorPorDefecto : configurado;
    }
}
