CREATE DATABASE IF NOT EXISTS dwes_08 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE dwes_08;

CREATE TABLE IF NOT EXISTS productos (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    precio DECIMAL(10, 2) NOT NULL
);
